### ISSUE TITLE
Resolving units attribute does not always work

### ISSUE THREAD

**Issue by domna** [FAIRmat-NFDI/pynxtools#139]
I'm trying to resolve a units attribute from an nxdl file.

I use ellipsometry and load the XML root like this (I use the `_get_nxdl_root` from the `verification` branch
```python
from pynxtools.dataconverter.verify import _get_nxdl_root
from pynxtools.nexus.nexus import get_node_at_nxdl_path, get_inherited_nodes
root = _get_nxdl_root('NXellipsometry')
```

Running this works fine
```python
get_node_at_nxdl_path('/ENTRY/INSTRUMENT/angle_of_incidence/units', None, root)
```

However, if I try to get another units attribute it fails
```python
get_node_at_nxdl_path('/ENTRY/INSTRUMENT/BEAM_PATH/focussing_probes/angular_spread/units', None, root)
```

with this error message
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/domna/fairmat/nomad-parser-nexus/pynxtools/nexus/nexus.py", line 987, in get_node_at_nxdl_path
    raise NxdlAttributeError(f"Attributes were not found for {nxdl_path}. "
pynxtools.nexus.nexus.NxdlAttributeError: Attributes were not found for /ENTRY/INSTRUMENT/BEAM_PATH/focussing_probes/angular_spread/units. Please check this entry in the template dictionary.
```

the field is present:
https://github.com/FAIRmat-NFDI/nexus_definitions/blob/a22cb8870ce6d5926e49576cd51dc306675a2ff3/contributed_definitions/NXellipsometry.nxdl.xml#L270

and executing
```python
get_node_at_nxdl_path('/ENTRY/INSTRUMENT/BEAM_PATH/focussing_probes/angular_spread', None, root)
```
is fine, too.

@sherjeelshabih Any ideas?

**Comment by sherjeelshabih** [comment]
Does this happen on a second run? Did you try loading the nxdl root and then searching for get_node_at_nxdl_path('/ENTRY/INSTRUMENT/BEAM_PATH/focussing_probes/angular_spread/units) directly? 

It could be that nexus.py changes the XML element you send to the func. And it no longer is the root.

**Comment by domna** [comment]
It happens also on first run:

```
❯ python
Python 3.8.13 (default, Sep  8 2022, 19:29:39)
[Clang 13.1.6 (clang-1316.0.21.2.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from pynxtools.dataconverter.verify import _get_nxdl_root
from pynxtools.nexus.nexus import get_node_at_nxdl_path, get_inherited_nodes
root = _get_nxdl_root('NXellipsometry')
>>> from pynxtools.nexus.nexus import get_node_at_nxdl_path, get_inherited_nodes
>>> root = _get_nxdl_root('NXellipsometry')
>>> get_node_at_nxdl_path('/ENTRY/INSTRUMENT/BEAM_PATH/focussing_probes/angular_spread/units', None, root)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/domna/fairmat/nomad-parser-nexus/pynxtools/nexus/nexus.py", line 987, in get_node_at_nxdl_path
    raise NxdlAttributeError(f"Attributes were not found for {nxdl_path}. "
pynxtools.nexus.nexus.NxdlAttributeError: Attributes were not found for /ENTRY/INSTRUMENT/BEAM_PATH/focussing_probes/angular_spread/units. Please check this entry in the template dictionary.
>>>
```

I was also still able to resolve `/ENTRY/INSTRUMENT/BEAM_PATH/focussing_probes/angular_spread` after the same key with units. This wouldn't work if the root would've been changed

**Comment by lukaspie** [comment]
This is still an open issue. I tried this by running

```python
from pynxtools.dataconverter.helpers import get_nxdl_root_and_path
from pynxtools.definitions.dev_tools.utils.nxdl_utils import get_inherited_nodes, get_node_at_nxdl_path

root, path= get_nxdl_root_and_path('NXoptical_spectroscopy')
get_node_at_nxdl_path('/ENTRY/INSTRUMENT/angle_of_incidence', None, root)
get_inherited_nodes('/ENTRY/INSTRUMENT/angle_of_incidence/units', None, root)
get_node_at_nxdl_path('/ENTRY/INSTRUMENT/angle_of_incidence/units', None, root)
```` 

The last line indeed fails with
```
NxdlAttributeNotFoundError(
pynxtools.definitions.dev_tools.utils.nxdl_utils.NxdlAttributeNotFoundError: Attributes were not found for /ENTRY/INSTRUMENT/angle_of_incidence/units. Please check this entry in the template dictionary.
```

Not sure if this is expected behavior.

**Comment by lukaspie** [comment]
By changing the `pynx read` (former `read_nexus`) tool to use the pynxtools internal NeXus tree description (see PR [777](https://github.com/FAIRmat-NFDI/pynxtools/pull/777)) we get rid of this issue.

The `@units` attribute on deeply nested fields no longer crashes or shows `[NOT IN SCHEMA]`; instead it is resolved via the parent field's NXDL unit category (e.g. `NX_ENERGY`) and displayed correctly.

```python
# pynx read arpes.nxs -d entry/instrument/analyser/pass_energy
# pynx read specs_xml_ref.nxs -d PBTTT_1_2_V__C1s/instrument/electronanalyzer/energydispersion/pass_energy

from pynxtools.annotator.annotator import Annotator
from pynxtools.nexus.handler import NexusFileHandler
import logging, sys

logger = logging.getLogger(__file__)
logger.setLevel(logging.DEBUG)
logger.addHandler(logging.StreamHandler(sys.stdout))
logger.propagate = False

# ARPES: pass_energy is 4 levels deep inside the analyser group.
# Before the fix, get_node_at_nxdl_path raised NxdlAttributeError
# and @units was either missing or shown as [NOT IN SCHEMA].
NexusFileHandler("201805_WSe2_arpes.nxs").process(
    Annotator(logger, documentation="entry/instrument/analyser/pass_energy")
)
# Output:
#         FIELD /entry/instrument/analyser/pass_energy  shape=()  dtype=int64
#           Concept   : NXarpes/ENTRY/INSTRUMENT/analyser/pass_energy  [REQUIRED]
#           @units = eV  [UNIT: NX_ENERGY]

# XPS: same field, 5 levels deep (electronanalyzer/energydispersion/pass_energy).
NexusFileHandler("specs_xml_ref.nxs").process(
    Annotator(
        logger,
        documentation="PBTTT_1_2_V__C1s/instrument/electronanalyzer/energydispersion/pass_energy",
    )
)
# Output:
#           FIELD /PBTTT_1_2_V__C1s/instrument/electronanalyzer/energydispersion/pass_energy  shape=()  dtype=float64
#             Concept   : NXmpes/ENTRY/INSTRUMENT/ELECTRONANALYZER/ENERGYDISPERSION/pass_energy  [RECOMMENDED]
#             @units = eV  [UNIT: NX_ENERGY]
```

The XPS file used above is the `specs_xml_ref.nxs` reference file from [pynxtools-xps](https://github.com/FAIRmat-NFDI/pynxtools-xps/blob/main/tests/data/specs_xml/specs_xml_ref.nxs).

**Comment by lukaspie** [comment]
This of course does not solve the issue with `get_node_at_nxdl_path`, but this will be deprecated and eventually removed
