### ISSUE TITLE
[Bug]: Writing a group with an enumeration updated in an appdef fails

### ISSUE THREAD

**Issue by domna** [FAIRmat-NFDI/pynxtools#210]
### What happened?

When I write the entry
```
/ENTRY[entry]/INSTRUMENT[instrument]/SOURCE[source_probe]/type = "HHG laser"
```

in an NXmpes appdef it fails with 
```
ValueError: The value at /ENTRY[entry]/INSTRUMENT[instrument]/SOURCE[source_probe]/type should be on of the following strings: [Spallation Neutron Source,Pulsed Reactor Neutron Source,Reactor Neutron Source,Synchrotron X-ray Source,Pulsed Muon Source,Rotating Anode X-ray,Fixed Tube X-ray,UV Laser,Free-Electron Laser,Optical Laser,Ion Source,UV Plasma Source,Metal Jet X-ray]
```

which are the enumeration fields of a generic NXsource. The entry `HHG laser` should be allowed in NXmpes/NXentry/NXinstrument/NXsource/type according to the [docs](https://fairmat-nfdi.github.io/nexus_definitions/classes/contributed_definitions/NXmpes.html#nxmpes).
I think this is related to the renaming of the group uppercase name from a simple `SOURCE` to `source_SOURCE`. I believe that this case is not handled properly in pynxtools.

### Relevant log output

```shell
dataconverter --reader mpes --nxdl NXmpes --input-file xarray_saved_small_calibration.h5 --input-file config_file.json
[info]: Path /ENTRY[entry]/PROCESS[process]/energy_calibration/coefficients not found. Skipping the entry.
The data entry corresponding to /ENTRY[entry]/data/energy is required and hasn't been supplied by the reader.
The data entry corresponding to /ENTRY[entry]/data/@signal is required and hasn't been supplied by the reader.
The data entry corresponding to /ENTRY[entry]/data/data is required and hasn't been supplied by the reader.
The data entry corresponding to /ENTRY[entry]/INSTRUMENT[instrument]/beam_TYPE/incident_energy is required and hasn't been supplied by the reader.
The data entry corresponding to /ENTRY[entry]/data/energy/@type is required and hasn't been supplied by the reader.
Traceback (most recent call last):
  File "/Users/domna/.pyenv/versions/pynxtools/bin/dataconverter", line 8, in <module>
    sys.exit(convert_cli())
  File "/Users/domna/.pyenv/versions/3.10.10/envs/pynxtools/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/Users/domna/.pyenv/versions/3.10.10/envs/pynxtools/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/Users/domna/.pyenv/versions/3.10.10/envs/pynxtools/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/domna/.pyenv/versions/3.10.10/envs/pynxtools/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/Users/domna/fairmat/nomad-parser-nexus/pynxtools/dataconverter/convert.py", line 378, in convert_cli
    convert(input_file, reader, nxdl, output, generate_template, fair, undocumented)
  File "/Users/domna/fairmat/nomad-parser-nexus/pynxtools/dataconverter/convert.py", line 251, in convert
    data = transfer_data_into_template(
  File "/Users/domna/fairmat/nomad-parser-nexus/pynxtools/dataconverter/convert.py", line 201, in transfer_data_into_template
    helpers.validate_data_dict(template, data, nxdl_root, logger=logger)
  File "/Users/domna/fairmat/nomad-parser-nexus/pynxtools/dataconverter/helpers.py", line 597, in validate_data_dict
    raise ValueError(
ValueError: The value at /ENTRY[entry]/INSTRUMENT[instrument]/SOURCE[source_probe]/type should be on of the following strings: [Spallation Neutron Source,Pulsed Reactor Neutron Source,Reactor Neutron Source,Synchrotron X-ray Source,Pulsed Muon Source,Rotating Anode X-ray,Fixed Tube X-ray,UV Laser,Free-Electron Laser,Optical Laser,Ion Source,UV Plasma Source,Metal Jet X-ray]
```
@lukaspie

**Comment by sherjeelshabih** [comment]
Can you try doing source_TYPE[source_type] instead of SOURCE[source_type]? That should work.

 I locally added a slight modification to the generate-template func that also adds the concept name for the name_RENAME style. But I don't know if it will start breaking other readers that don't have tests, etc.
