### ISSUE TITLE
[Bug]: NeXus parser (nomad) getting error while reading unit `degree` from pint units 

### ISSUE THREAD

**Issue by RubelMozumder** [FAIRmat-NFDI/pynxtools#395]
### Contact Details

rubel.mozumder@outlook.com

### What happened?

Error massage:
```
ERROR    nomad.processing     2024-07-29T09:46:26 could not normalize section
  - exception: Traceback (most recent call last):
      File "/home/rubel/NOMAD-FAIRmat/GH/pynxtools/src/pynxtools/dataconverter/writer.py", line 324, in _put_data_into_hdf5
        add_units_key(self.output_nexus[path_hdf5], path)
      File "/home/rubel/NOMAD-FAIRmat/GH/pynxtools/src/pynxtools/dataconverter/writer.py", line 264, in add_units_key
        dataset.attrs["units"] = self.data[units_key]
      File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
      File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
      File "/home/rubel/NOMAD-FAIRmat/GH/nomad-measurements/.PE9/lib/python3.9/site-packages/h5py/_hl/attrs.py", line 104, in __setitem__
        self.create(name, data=value)
      File "/home/rubel/NOMAD-FAIRmat/GH/nomad-measurements/.PE9/lib/python3.9/site-packages/h5py/_hl/attrs.py", line 182, in create
        htype = h5t.py_create(original_dtype, logical=True)
      File "h5py/h5t.pyx", line 1663, in h5py.h5t.py_create
      File "h5py/h5t.pyx", line 1687, in h5py.h5t.py_create
      File "h5py/h5t.pyx", line 1747, in h5py.h5t.py_create
    TypeError: Object dtype dtype('O') has no native HDF5 equivalent
    ```
    
To write a dataset in a hdf5 file and using `degree` as a unit for a quantity in dataset, the error can be reproduced.

Probably, the error is coming from hdf5 lib, as `pint` lib returns a degree symbol `o` instead of string and hdf5 lib unable to decode or unable detect common data type.

**Comment by mkuehbach** [comment]
The proper usage of pint and h5py for °C is like this:
e.g. 
```
import pint
from pint import UnitRegistry
ureg = UnitRegistry()
# assume above lines have been called somewhere else then you can do
T = ureg.Quantity(20.0, ureg.degC)
print(T.units)
```

T itself is an object, if you want to write the unit via h5py and say pynxtools' 
```
template[SOMEPATH/temperature/@units] = T.units
```

@Do these hints help @RubelMozumder ?
